env:
  - CGO_ENABLED=0
  - RELEASE_BUILDS=dist/zettel_darwin_amd64/zettel dist/zettel_linux_amd64/zettel dist/zettel_windows_amd64/zettel.exe dist/zettel_linux_arm64/zettel 
builds:
  - binary: zettel
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    dir: cmd/zettel
    ldflags:
      - -s -w -X "main.buildVersion={{ .Tag }} ({{ .ShortCommit }} {{ .Date }})"
    hooks:
      pre: go mod download

archives:
  - format: tar.gz
    files:
      - README.md
      - LICENSE
